name: code quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
jobs:
  clippy_check:
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: clone code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: install Rust
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
        with:
          # Sync with rust-toolchain.toml
          toolchain: 1.82
          override: true
          components: rustfmt, clippy
      - name: lint
        run: cargo clippy --features test_ci --exclude grit-wasm-bindings --workspace --locked -- -D warnings
      - name: format
        run: cargo fmt -- --check
